# Exported from Render on 2024-07-14T21:49:52Z
services:
- type: web
  name: Xstro
  runtime: docker
  repo: https://github.com/AstroFx0011/Xstro
  plan: free
  envVars:
  - key: SESSION_ID
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
 
